In [64]:
#KIRUTHIKASHREE A

In [65]:
import pandas as pd

In [66]:
import numpy as np

In [67]:
import matplotlib.pyplot as plt

In [68]:
art=pd.read_csv("C:/Users/kirut/Downloads/sales_data.csv")

In [69]:
art.columns

Index(['OrderID', 'Date', 'Product', 'Category', 'Quantity', 'UnitPrice'], dtype='str')

In [102]:
#loc & iloc
art.loc[0]

OrderID             1031
Date          2026-01-01
Product       Smartphone
Category     Electronics
Quantity               3
UnitPrice            800
Sales                803
Name: 0, dtype: object

In [110]:
art.loc[[0],art.columns[0:20]]

   OrderID        Date     Product     Category  Quantity  UnitPrice  Sales
0     1031  2026-01-01  Smartphone  Electronics         3        800    803

In [106]:
art.iloc[0:10,0:5]

   OrderID        Date     Product     Category  Quantity
0     1031  2026-01-01  Smartphone  Electronics         3
1     1100  2026-01-02  Headphones  Accessories         2
2     1028  2026-01-02      Laptop  Electronics         2
3     1089  2026-01-02      Laptop  Electronics         3
4     1023  2026-01-02      Tablet  Electronics         4
5     1072  2026-01-02  Smartphone  Electronics         4
6     1055  2026-01-03  Headphones  Accessories         1
7     1020  2026-01-03      Laptop  Electronics         1
8     1082  2026-01-03  Smartphone  Electronics         4
9     1085  2026-01-04      Laptop  Electronics         1

In [73]:
#operators
art[art["Quantity"]>2]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
8      1082  2026-01-03  Smartphone  Electronics         4        800
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
17     1061  2026-01-07  Headphones  Accessories         3        150
20     1001  2026-01-07  Smartphone  Electronics         4        800
21     1009  2026-01-07  Smartphone  Electronics         4        800
22     1080  2026-01-08  Headphones  Accessories         3        150
24     1087  2026-01-08      Laptop  Electronics         4       1200
25     1006  2026-01-08  Smartwatch  Accessories         4        250
26     1060  2026-01-09  Smartwatch  Accessories         3        250
27     1069  2026-01-09      Tablet  Electronics         4        450
28     1093  2026-01-10      Tablet  Electronics         3        450
30     1014  2026-01-11  Smartwatch  Accessories         4        250
31     1005  2026-01-11  Smartwatch  Accessories         4        250
33     1036  2026-01-12  Headphones  Accessories         3        150
36     1025  2026-01-12      Laptop  Electronics         3       1200
37     1099  2026-01-12  Smartphone  Electronics         3        800
38     1078  2026-01-12  Headphones  Accessories         3        150
39     1083  2026-01-14  Headphones  Accessories         3        150
40     1066  2026-01-14  Headphones  Accessories         4        150
41     1081  2026-01-15      Tablet  Electronics         4        450
42     1048  2026-01-15      Laptop  Electronics         3       1200
44     1045  2026-01-15      Tablet  Electronics         3        450
45     1075  2026-01-15  Smartwatch  Accessories         4        250
46     1044  2026-01-16      Laptop  Electronics         4       1200
48     1084  2026-01-17      Laptop  Electronics         4       1200
49     1062  2026-01-18  Smartwatch  Accessories         4        250
52     1067  2026-01-18  Smartwatch  Accessories         3        250
55     1050  2026-01-19  Smartphone  Electronics         3        800
57     1002  2026-01-20  Headphones  Accessories         3        150
58     1073  2026-01-20  Smartwatch  Accessories         4        250
62     1071  2026-01-21  Smartphone  Electronics         3        800
69     1052  2026-01-23      Laptop  Electronics         3       1200
71     1015  2026-01-24      Laptop  Electronics         4       1200
73     1019  2026-01-24      Laptop  Electronics         3       1200
74     1054  2026-01-25  Smartphone  Electronics         4        800
78     1033  2026-01-26      Laptop  Electronics         4       1200
80     1098  2026-01-26      Tablet  Electronics         3        450
83     1040  2026-01-27      Tablet  Electronics         4        450
84     1029  2026-01-28      Tablet  Electronics         4        450
86     1076  2026-01-28  Headphones  Accessories         3        150
87     1074  2026-01-28      Laptop  Electronics         3       1200
88     1042  2026-01-28      Tablet  Electronics         4        450
90     1079  2026-01-29  Headphones  Accessories         3        150
91     1003  2026-01-29  Headphones  Accessories         3        150
94     1007  2026-01-29  Smartphone  Electronics         4        800
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

In [74]:
art[art["Quantity"]<2]

    OrderID        Date     Product     Category  Quantity  UnitPrice
6      1055  2026-01-03  Headphones  Accessories         1        150
7      1020  2026-01-03      Laptop  Electronics         1       1200
9      1085  2026-01-04      Laptop  Electronics         1       1200
34     1051  2026-01-12      Tablet  Electronics         1        450
35     1032  2026-01-12  Smartphone  Electronics         1        800
50     1086  2026-01-18      Laptop  Electronics         1       1200
61     1008  2026-01-21  Smartwatch  Accessories         1        250
63     1022  2026-01-21  Headphones  Accessories         1        150
65     1034  2026-01-22  Headphones  Accessories         1        150
66     1021  2026-01-22      Laptop  Electronics         1       1200
67     1095  2026-01-22      Laptop  Electronics         1       1200
68     1092  2026-01-22      Laptop  Electronics         1       1200
70     1012  2026-01-23  Headphones  Accessories         1        150
72     1024  2026-01-24      Tablet  Electronics         1        450
76     1064  2026-01-25      Tablet  Electronics         1        450
77     1070  2026-01-26  Headphones  Accessories         1        150
81     1010  2026-01-26      Laptop  Electronics         1       1200
82     1039  2026-01-27  Smartwatch  Accessories         1        250
85     1065  2026-01-28  Smartwatch  Accessories         1        250
92     1096  2026-01-29  Smartwatch  Accessories         1        250
93     1035  2026-01-29      Laptop  Electronics         1       1200
95     1026  2026-01-30      Tablet  Electronics         1        450

In [75]:
art[art["UnitPrice"]<=150]

    OrderID        Date     Product     Category  Quantity  UnitPrice
1      1100  2026-01-02  Headphones  Accessories         2        150
6      1055  2026-01-03  Headphones  Accessories         1        150
17     1061  2026-01-07  Headphones  Accessories         3        150
19     1077  2026-01-07  Headphones  Accessories         2        150
22     1080  2026-01-08  Headphones  Accessories         3        150
29     1041  2026-01-10  Headphones  Accessories         2        150
32     1013  2026-01-11  Headphones  Accessories         2        150
33     1036  2026-01-12  Headphones  Accessories         3        150
38     1078  2026-01-12  Headphones  Accessories         3        150
39     1083  2026-01-14  Headphones  Accessories         3        150
40     1066  2026-01-14  Headphones  Accessories         4        150
54     1011  2026-01-19  Headphones  Accessories         2        150
57     1002  2026-01-20  Headphones  Accessories         3        150
63     1022  2026-01-21  Headphones  Accessories         1        150
64     1059  2026-01-21  Headphones  Accessories         2        150
65     1034  2026-01-22  Headphones  Accessories         1        150
70     1012  2026-01-23  Headphones  Accessories         1        150
77     1070  2026-01-26  Headphones  Accessories         1        150
86     1076  2026-01-28  Headphones  Accessories         3        150
90     1079  2026-01-29  Headphones  Accessories         3        150
91     1003  2026-01-29  Headphones  Accessories         3        150
96     1090  2026-01-30  Headphones  Accessories         2        150

In [76]:
art[art["OrderID"]>=1020]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[81 rows x 6 columns]

In [77]:
art[(art["Quantity"]>2)&(art["UnitPrice"]>100)]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
8      1082  2026-01-03  Smartphone  Electronics         4        800
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
17     1061  2026-01-07  Headphones  Accessories         3        150
20     1001  2026-01-07  Smartphone  Electronics         4        800
21     1009  2026-01-07  Smartphone  Electronics         4        800
22     1080  2026-01-08  Headphones  Accessories         3        150
24     1087  2026-01-08      Laptop  Electronics         4       1200
25     1006  2026-01-08  Smartwatch  Accessories         4        250
26     1060  2026-01-09  Smartwatch  Accessories         3        250
27     1069  2026-01-09      Tablet  Electronics         4        450
28     1093  2026-01-10      Tablet  Electronics         3        450
30     1014  2026-01-11  Smartwatch  Accessories         4        250
31     1005  2026-01-11  Smartwatch  Accessories         4        250
33     1036  2026-01-12  Headphones  Accessories         3        150
36     1025  2026-01-12      Laptop  Electronics         3       1200
37     1099  2026-01-12  Smartphone  Electronics         3        800
38     1078  2026-01-12  Headphones  Accessories         3        150
39     1083  2026-01-14  Headphones  Accessories         3        150
40     1066  2026-01-14  Headphones  Accessories         4        150
41     1081  2026-01-15      Tablet  Electronics         4        450
42     1048  2026-01-15      Laptop  Electronics         3       1200
44     1045  2026-01-15      Tablet  Electronics         3        450
45     1075  2026-01-15  Smartwatch  Accessories         4        250
46     1044  2026-01-16      Laptop  Electronics         4       1200
48     1084  2026-01-17      Laptop  Electronics         4       1200
49     1062  2026-01-18  Smartwatch  Accessories         4        250
52     1067  2026-01-18  Smartwatch  Accessories         3        250
55     1050  2026-01-19  Smartphone  Electronics         3        800
57     1002  2026-01-20  Headphones  Accessories         3        150
58     1073  2026-01-20  Smartwatch  Accessories         4        250
62     1071  2026-01-21  Smartphone  Electronics         3        800
69     1052  2026-01-23      Laptop  Electronics         3       1200
71     1015  2026-01-24      Laptop  Electronics         4       1200
73     1019  2026-01-24      Laptop  Electronics         3       1200
74     1054  2026-01-25  Smartphone  Electronics         4        800
78     1033  2026-01-26      Laptop  Electronics         4       1200
80     1098  2026-01-26      Tablet  Electronics         3        450
83     1040  2026-01-27      Tablet  Electronics         4        450
84     1029  2026-01-28      Tablet  Electronics         4        450
86     1076  2026-01-28  Headphones  Accessories         3        150
87     1074  2026-01-28      Laptop  Electronics         3       1200
88     1042  2026-01-28      Tablet  Electronics         4        450
90     1079  2026-01-29  Headphones  Accessories         3        150
91     1003  2026-01-29  Headphones  Accessories         3        150
94     1007  2026-01-29  Smartphone  Electronics         4        800
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

In [78]:
art[(art["Quantity"]>2)|(art["OrderID"]>100)]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [79]:
art[~(art["OrderID"])<1000]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [113]:
#ascending & desending
art.sort_values("Category",ascending=True)

    OrderID        Date     Product     Category  Quantity  UnitPrice  Sales
49     1062  2026-01-18  Smartwatch  Accessories         4        250    254
82     1039  2026-01-27  Smartwatch  Accessories         1        250    251
29     1041  2026-01-10  Headphones  Accessories         2        150    152
30     1014  2026-01-11  Smartwatch  Accessories         4        250    254
64     1059  2026-01-21  Headphones  Accessories         2        150    152
..      ...         ...         ...          ...       ...        ...    ...
37     1099  2026-01-12  Smartphone  Electronics         3        800    803
36     1025  2026-01-12      Laptop  Electronics         3       1200   1203
35     1032  2026-01-12  Smartphone  Electronics         1        800    801
44     1045  2026-01-15      Tablet  Electronics         3        450    453
99     1047  2026-01-30      Tablet  Electronics         3        450    453

[100 rows x 7 columns]

In [115]:
art.sort_values("OrderID", ascending=False)

    OrderID        Date     Product     Category  Quantity  UnitPrice  Sales
1      1100  2026-01-02  Headphones  Accessories         2        150    152
37     1099  2026-01-12  Smartphone  Electronics         3        800    803
80     1098  2026-01-26      Tablet  Electronics         3        450    453
51     1097  2026-01-18      Laptop  Electronics         2       1200   1202
92     1096  2026-01-29  Smartwatch  Accessories         1        250    251
..      ...         ...         ...          ...       ...        ...    ...
31     1005  2026-01-11  Smartwatch  Accessories         4        250    254
43     1004  2026-01-15      Laptop  Electronics         2       1200   1202
91     1003  2026-01-29  Headphones  Accessories         3        150    153
57     1002  2026-01-20  Headphones  Accessories         3        150    153
20     1001  2026-01-07  Smartphone  Electronics         4        800    804

[100 rows x 7 columns]

In [111]:
art.sort_values(by=["Category","Product"],ascending=[True,False])

    OrderID        Date     Product     Category  Quantity  UnitPrice  Sales
12     1017  2026-01-04  Smartwatch  Accessories         3        250    253
13     1063  2026-01-04  Smartwatch  Accessories         4        250    254
14     1056  2026-01-05  Smartwatch  Accessories         4        250    254
15     1091  2026-01-06  Smartwatch  Accessories         4        250    254
25     1006  2026-01-08  Smartwatch  Accessories         4        250    254
..      ...         ...         ...          ...       ...        ...    ...
73     1019  2026-01-24      Laptop  Electronics         3       1200   1203
78     1033  2026-01-26      Laptop  Electronics         4       1200   1204
81     1010  2026-01-26      Laptop  Electronics         1       1200   1201
87     1074  2026-01-28      Laptop  Electronics         3       1200   1203
93     1035  2026-01-29      Laptop  Electronics         1       1200   1201

[100 rows x 7 columns]

In [83]:
art["Sales"]=art["Quantity"]*art["UnitPrice"]
art.head()

   OrderID        Date     Product     Category  Quantity  UnitPrice  Sales
0     1031  2026-01-01  Smartphone  Electronics         3        800   2400
1     1100  2026-01-02  Headphones  Accessories         2        150    300
2     1028  2026-01-02      Laptop  Electronics         2       1200   2400
3     1089  2026-01-02      Laptop  Electronics         3       1200   3600
4     1023  2026-01-02      Tablet  Electronics         4        450   1800

In [85]:
art["Sales"]=art["Quantity"]+art["UnitPrice"]
art.tail()

    OrderID        Date     Product     Category  Quantity  UnitPrice  Sales
95     1026  2026-01-30      Tablet  Electronics         1        450    451
96     1090  2026-01-30  Headphones  Accessories         2        150    152
97     1049  2026-01-30  Smartwatch  Accessories         4        250    254
98     1046  2026-01-30  Smartwatch  Accessories         4        250    254
99     1047  2026-01-30      Tablet  Electronics         3        450    453

In [89]:
#Aggregate
art.groupby("Quantity")["Category"].min()

Quantity
1    Accessories
2    Accessories
3    Accessories
4    Accessories
Name: Category, dtype: str

In [90]:
art.groupby("Quantity")["Category"].max()

Quantity
1    Electronics
2    Electronics
3    Electronics
4    Electronics
Name: Category, dtype: str

In [92]:
art.groupby("Quantity")["Sales"].sum()

Quantity
1    13972
2    12192
3    14378
4    17424
Name: Sales, dtype: int64

In [93]:
art.groupby("Quantity")["UnitPrice"].sum()

Quantity
1    13950
2    12150
3    14300
4    17300
Name: UnitPrice, dtype: int64

In [98]:
art.groupby("Quantity")["Sales"].mean()

Quantity
1    635.090909
2    580.571429
3    553.000000
4    562.064516
Name: Sales, dtype: float64

In [97]:
art.groupby("Quantity")["UnitPrice"].count()

Quantity
1    22
2    21
3    26
4    31
Name: UnitPrice, dtype: int64

In [101]:
art.groupby("UnitPrice")["Sales"].std()

UnitPrice
150     0.882735
250     1.234376
450     1.196486
800     0.987096
1200    1.144552
Name: Sales, dtype: float64